String HOME_SCREEN='/HomeScreen';
String SETUP_SPLASH='/SetupSplashScreen';
String VIDEO_SPALSH='/VideoSplashScreen';



String SETTINGS_DATA ='SETTINGS_DATA';
String CURRENT_LANGUAGE_CODE ='CURRENT_LANGUAGE_CODE';
String CURRENT_COUNTRY_CODE ='CURRENT_COUNTRY_CODE';